version: '3.9'
services:
  app:
    container_name: app
    build: ./app
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
  db:
    container_name: db
    build: ./db
    volumes: 
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"



