version: '3.9'
services:
  app:
    container_name: app
    build: ./app
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    depends_on:
      - db
    env_file: ./app/.env
    networks:
      - app-net
  db:
    container_name: db
    build: ./db
    env_file: ./db/.env
    ports:
      - "3306:3306"
    networks:
      - app-net
networks:
  app-net:
    driver: bridge

